### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gabrielodom** [songxiaoyu/iProFun#2]
Hi folks,
When installing this package from GitHub, I receive the following error:

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'metRology'
```

I understand how to fix this issue (just install the `metRology` package first), but I thought you should know that your `DESCRIPTION` file does not include this package as a dependency.

**Comment by JiayiJi** [comment]
Thanks for the reminder! We will update our package and add `metRology` package in our `DESCRIPTION` file as a dependency!
