### ISSUE TITLE
iProFun.eFDR : no Gene_fdr element

### ISSUE THREAD

**Issue by sarahbonnin** [songxiaoyu/iProFun#3]
Hello,

I am trying to run iProFun with 2 outcomes and 2 predictors.

```
  # Pre-specified prior proportion of non-null statistics
  pi1 <- 0.05
  # Linear regression on more than one outcome data types
  reg.all <- iProFun.reg(yList=yList, xList=xList, covariates=covariates,
                         var.ID=c("Gene_ID"),
                         seed=12)

  # reformat output of iProFun.reg
  summ <- multi.omic.reg.summary(reg.out.list=reg.all, var.ID="Gene_ID")
  
  # Calculates the posterior probabilities of association patterns from regression summaries from multiple data types
  prob <- iProFun.prob(Reg.Sum=summ, NoProbXIndex=NULL, pi1=pi1)

  # Empirical FDR controlled discoveries for all outcomes
  eFDR <- iProFun.eFDR(reg.all=reg.all, yList=yList, xList=xList, covariates=covariates, pi1=pi1,
                       NoProbXIndex=NULL,filter=c(0,0),
                       permutate_number=2, var.ID=c("Gene_ID"),
                       grids = seq(0.01, 0.99, by=0.01),fdr = 0.1, PostCut=0.75, seed=12)
```

According to the documentation, the output of `iProFun.eFDR` should contain the following elements: eFDR.grid, fdr_cutPob, No.Identified.filter, No.Identified.no.filter, Gene_fdr.

I do not however have the "Gene_fdr" as an output, here is what I get: eFDR.grid, fdr_cutPob, No.Identified.no.filter, No.Identified.filter, PostProb, eFDR.no.filter, sig.no.filter, sig.filter, xNames.

I understand that the "Gene_fdr" would be a summary per gene of all the outcomes, so I would be interested in that but I don't have it...
Could you please let me know who to get it? I'm not sure how to interpret all fields in order to get summary statistics per gene and not per outcome.

I am running iProFun v0.2.0 under R v4.1.0.

Thank you!

Best wishes

**Comment by sarahbonnin** [comment]
Hi again,
could anyone help about this issue?
Thank you!

**Comment by songxiaoyu** [comment]
Sorry I just learned that people can post questions in "Issues". iProFun has been systematically revised. Please let me know if you continue using it and seeing issues. Thanks.
